jamlab-ansible: enable pulling specific branch even if -r is not set

diff --git a/bin/jamlab-ansible b/bin/jamlab-ansible
--- a/bin/jamlab-ansible
+++ b/bin/jamlab-ansible
@@ -91,15 +91,17 @@ then
     fi
 fi
 
+# Checkout default or specified branch
+cd $ansible_path
+git checkout $branch
+if [ $? -ne 0 ]; then
+    echo -e "[ ${COLOR_RED_BOLD}FATAL${COLOR_RESET} ] Unable to checkout branch $branch at $ANSIBLE_REPO_URL" >&2
+    exit 1
+fi
+
 # Pull latest if argument set
 if [[ $refresh == true ]]
 then
-    cd $ansible_path
-    git checkout $branch
-    if [ $? -ne 0 ]; then
-        echo -e "[ ${COLOR_RED_BOLD}FATAL${COLOR_RESET} ] Unable to checkout branch $branch at $ANSIBLE_REPO_URL" >&2
-        exit 1
-    fi
     git pull
     if [ $? -ne 0 ]; then
         echo -e "[ ${COLOR_YELLOW_BOLD}WARNING${COLOR_RESET} ] Unable to pull latest branch $branch at $ANSIBLE_REPO_URL"
