allow localhost communication between nomad,consul (#1)
* consul: use http on localhost
* bin: git pull before gco with jamlab-ansible
* consul: advertise dns on ipv4
* consul: client bind to eth0
* nomad: use official service file
* consul: enable grpc on ipv4

diff --git a/bin/jamlab-ansible b/bin/jamlab-ansible
--- a/bin/jamlab-ansible
+++ b/bin/jamlab-ansible
@@ -76,14 +76,6 @@ then
     fi
 fi
 
-# Checkout default or specified branch
-cd $ansible_path
-git checkout $branch
-if [ $? -ne 0 ]; then
-    echo -e "[ ${COLOR_RED_BOLD}FATAL${COLOR_RESET} ] Unable to checkout branch $branch at $ANSIBLE_REPO_URL" >&2
-    exit 1
-fi
-
 # Pull latest if argument set
 if [[ $refresh == true ]]
 then
@@ -92,6 +84,14 @@ then
         echo -e "[ ${COLOR_YELLOW_BOLD}WARNING${COLOR_RESET} ] Unable to pull latest branch $branch at $ANSIBLE_REPO_URL"
         echo -e "[ ${COLOR_YELLOW_BOLD}WARNING${COLOR_RESET} ] Continuing without pulling latest..."
     fi
+fi
+
+# Checkout default or specified branch
+cd $ansible_path
+git checkout $branch
+if [ $? -ne 0 ]; then
+    echo -e "[ ${COLOR_RED_BOLD}FATAL${COLOR_RESET} ] Unable to checkout branch $branch at $ANSIBLE_REPO_URL" >&2
+    exit 1
 fi
 
 # Display last commit
